security:
    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: home

    providers:
        main:
            entity:
                class: AppBundle\Entity\User
                property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            iterations: 5000

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/utilisateur, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER