<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FineRepository extends EntityRepository
{
    // public function allResults()
    // {
    //     $qb=$this->createQueryBuilder('f');
    //     // $qb->select('b','a','c','s')
    //     // ->leftJoin('b.dessinateur', 'a')
    //     // ->leftJoin('b.scenariste', 'c')
    //     // ->leftJoin('b.coloriste', 's');
    //     $query=$qb->getQuery();
    //     // $query->setMaxResults(10);
    //     $result=$query->getResult();

    //     return $result;
    // }
}
