<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelBookOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelBookOrderRepository extends EntityRepository
{

     /*public function panierResults(){
        $qd=$this->createQueryBuilder('r');
        $qd->select('r','c')
        ->leftJoin('r.order', 'c');
        $query=$qd->getQuery();
        $result=$query->getResult();


        return $result;
    }*/
}
