<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelBookOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelBookOrderRepository extends EntityRepository
{
}
